/*
throw keyword is used to manually throw an exception inside a method
 */
package dheeraj.exceptionhandling;

public class ThrowExample {
	public static void main(String[] args) {
		throw new ArithmeticException("Division by zero is not allowed");
	}
}
